### PR TITLE
Fix: Hardcoded string replaced by string resource.

### PR DESCRIPTION
**Pull request by adityaofficial10**
Fixes issue: https://github.com/odk-x/tool-suite-X/issues/190

**What changes have been made?**
- The mentioned hardcoded string has been replaced by its corresponding string resource.

### CODE REVIEW

**Comment by linl33** [comment]
@adityaofficial10 Can you include your changes to `strings.xml` as well?

**Comment by adityaofficial10** [comment]
@linl33 
Thanks for the review.
I'll do the needful.

**Review by wbrunette — CHANGES_REQUESTED** [review]
as @linl33 requested, please add the changes to strings.xml

**Comment by adityaofficial10** [comment]
@wbrunette 
Sure, i'm working on it.

**Comment by linl33** [comment]
@adityaofficial10 Could you give us an update on this? Let us know if you're having any difficulties.

**Pull request closed without merging**
